version: '2'
services:
        db:
                image: mysql
                environment:
                        MYSQL_ROOT_PASSWORD: secret
                        MYSQL_DATABASE: fedora3
                        MYSQL_USER: fedoraAdmin
                        MYSQL_PASSWORD: secret
                volumes:
                        - mysql_data:/var/lib/mysql
        search: 
                image: solr
                volumes:
                        - search_data:/mnt/solr
                command: /catalina-run.sh
        triplestore:
                image: fuseki
                volumes:
                        - triplestore_data:/mnt/fuseki
                command: /catalina-run.sh
        fedora:
                depends_on:
                        - db
                        - search
                        - triplestore
                image: fedora3_karaf
                volumes:
                        - fedora_data:/mnt/ingest
                ports:
                        - "80:8080"
                links:
                        - db
                        - search
                        - triplestore
                command: /root/runall.sh
volumes:
        mysql_data:
                driver: "local"
        fedora_data:
                driver: "local"
        search_data:
                driver: "local"
        triplestore_data:
                driver: "local"
